language: ruby
script: "bundle exec cucumber"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode
env: TEST=true TRAVIS=true
gemfile:
  - Gemfile
notifications:
  webhooks:
    - https://idobata.io/hook/travis_ci/a7668cc4-aa10-4871-b8e4-095e117ad464
